# -*- coding: utf-8 -*-
"""Speech to Text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zntfcYvv18fgYGTUZVK6jB5k0XQsyd0l

**Installing Speech Recognition library:**
"""

pip install SpeechRecognition

"""**Importing the library and initializing recognizer class (for recognizing speech):**"""

import speech_recognition as sr

r = sr.Recognizer()

"""**Converting the Audio:**"""

with sr.AudioFile("/content/drive/My Drive/Data/Audio to Text/Voice 1.wav") as source:
    audio_text = r.record(source)

    #recognize() method will throw an error if the API is unreachable, hence using exception handling
    try:
        text = r.recognize_google(audio_text)                       #Using google speech recognition
        print("Converting audio transcripts into text... \n\n{}".format(text))
    
    except:
        print("Sorry could not recognize what you said")

#If using microphone to record audio:
#with sr.Microphone() as source:
    #audio_text = r.listen(source)
    #(rest similar to above)

"""**Let's say now you want to get all the nouns from the extracted text:**"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

def preprocess(sent):
    sent = nltk.word_tokenize(sent)
    sent = nltk.pos_tag(sent)
    return sent

nltk.download("punkt")
nltk.download('averaged_perceptron_tagger')

sent = preprocess(text)
noun = []

for words, tag in sent:
    if tag == "NN":
        noun.append(words)

noun

